spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

server:
  servlet:
    encoding:
      force: true

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    groupId:
      artifactId: info